title: Christopher L. Jeffries
description: Showcase my skills to my future employer
show_downloads: true
google_analytics:
# IMPORTANT: Remove or comment out the theme below
# theme: jekyll-theme-hacker


